apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "egglogu.fullname" . }}-beat
  labels:
    {{- include "egglogu.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: {{ .Values.beat.replicaCount }}
  selector:
    matchLabels:
      {{- include "egglogu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        {{- include "egglogu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      serviceAccountName: {{ include "egglogu.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - -A
            - src.worker
            - beat
            - --loglevel=info
          envFrom:
            - configMapRef:
                name: {{ include "egglogu.fullname" . }}-config
            - secretRef:
                name: {{ .Values.credentials.ref }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
