apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "egglogu.fullname" . }}-worker
  labels:
    {{- include "egglogu.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "egglogu.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "egglogu.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "egglogu.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - -A
            - src.worker
            - worker
            - --loglevel=info
            - --concurrency=4
            - -Q
            - {{ .Values.app.celeryQueues }}
          envFrom:
            - configMapRef:
                name: {{ include "egglogu.fullname" . }}-config
            - secretRef:
                name: {{ .Values.credentials.ref }}
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - src.worker
                - inspect
                - ping
                - --timeout=5
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
