"""add_erp_modules_inventory_grading_po_audit_compliance_costcenter

Revision ID: a422e710575a
Revises: a1b2c3d4e567
Create Date: 2026-02-24 20:38:16.112314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a422e710575a'
down_revision: Union[str, None] = 'a1b2c3d4e567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
