"""initial

Revision ID: 991ed48bc5a9
Revises: 
Create Date: 2026-02-10 00:24:38.958444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991ed48bc5a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_organization_id'), 'checklist_items', ['organization_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_small', sa.Float(), nullable=True),
    sa.Column('price_medium', sa.Float(), nullable=True),
    sa.Column('price_large', sa.Float(), nullable=True),
    sa.Column('price_xl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('environment_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('ammonia_ppm', sa.Float(), nullable=True),
    sa.Column('light_lux', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('heat_stress_idx', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_readings_organization_id'), 'environment_readings', ['organization_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_organization_id'), 'expenses', ['organization_id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('owm_api_key', sa.String(length=100), nullable=True),
    sa.Column('mqtt_broker', sa.String(length=300), nullable=True),
    sa.Column('mqtt_user', sa.String(length=100), nullable=True),
    sa.Column('mqtt_pass', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_organization_id'), 'farms', ['organization_id'], unique=False)
    op.create_table('feed_purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_purchases_organization_id'), 'feed_purchases', ['organization_id'], unique=False)
    op.create_table('iot_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensor_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_readings_organization_id'), 'iot_readings', ['organization_id'], unique=False)
    op.create_table('logbook_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logbook_entries_organization_id'), 'logbook_entries', ['organization_id'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_desc', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_organization_id'), 'personnel', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'vet', 'viewer', name='role'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('forecast_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_organization_id'), 'weather_cache', ['organization_id'], unique=False)
    op.create_table('flocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('initial_count', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('housing_type', sa.String(length=100), nullable=True),
    sa.Column('target_curve', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flocks_farm_id'), 'flocks', ['farm_id'], unique=False)
    op.create_index(op.f('ix_flocks_organization_id'), 'flocks', ['organization_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dozens', sa.Float(), nullable=False),
    sa.Column('egg_size', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_client_id'), 'incomes', ['client_id'], unique=False)
    op.create_index(op.f('ix_incomes_organization_id'), 'incomes', ['organization_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_client_id'), 'receivables', ['client_id'], unique=False)
    op.create_index(op.f('ix_receivables_organization_id'), 'receivables', ['organization_id'], unique=False)
    op.create_table('breed_curves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('expected_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_curves_flock_id'), 'breed_curves', ['flock_id'], unique=False)
    op.create_index(op.f('ix_breed_curves_organization_id'), 'breed_curves', ['organization_id'], unique=False)
    op.create_table('daily_production',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_eggs', sa.Integer(), nullable=False),
    sa.Column('broken', sa.Integer(), nullable=False),
    sa.Column('small', sa.Integer(), nullable=False),
    sa.Column('medium', sa.Integer(), nullable=False),
    sa.Column('large', sa.Integer(), nullable=False),
    sa.Column('xl', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('egg_mass_g', sa.Float(), nullable=True),
    sa.Column('water_liters', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_production_date'), 'daily_production', ['date'], unique=False)
    op.create_index(op.f('ix_daily_production_flock_id'), 'daily_production', ['flock_id'], unique=False)
    op.create_index(op.f('ix_daily_production_organization_id'), 'daily_production', ['organization_id'], unique=False)
    op.create_table('feed_consumption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feed_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_consumption_flock_id'), 'feed_consumption', ['flock_id'], unique=False)
    op.create_index(op.f('ix_feed_consumption_organization_id'), 'feed_consumption', ['organization_id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hen_day_pct', sa.Float(), nullable=True),
    sa.Column('fcr', sa.Float(), nullable=True),
    sa.Column('mortality_pct', sa.Float(), nullable=True),
    sa.Column('avg_egg_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_snapshots_flock_id'), 'kpi_snapshots', ['flock_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_organization_id'), 'kpi_snapshots', ['organization_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_flock_id'), 'medications', ['flock_id'], unique=False)
    op.create_index(op.f('ix_medications_organization_id'), 'medications', ['organization_id'], unique=False)
    op.create_table('outbreaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('disease', sa.String(length=200), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbreaks_flock_id'), 'outbreaks', ['flock_id'], unique=False)
    op.create_index(op.f('ix_outbreaks_organization_id'), 'outbreaks', ['organization_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_flock_id'), 'predictions', ['flock_id'], unique=False)
    op.create_index(op.f('ix_predictions_organization_id'), 'predictions', ['organization_id'], unique=False)
    op.create_table('stress_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('heat', 'cold', 'noise', 'predator', 'handling', 'other', name='stresstype'), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_events_flock_id'), 'stress_events', ['flock_id'], unique=False)
    op.create_index(op.f('ix_stress_events_organization_id'), 'stress_events', ['organization_id'], unique=False)
    op.create_table('vaccines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flock_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_flock_id'), 'vaccines', ['flock_id'], unique=False)
    op.create_index(op.f('ix_vaccines_organization_id'), 'vaccines', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccines_organization_id'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_flock_id'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_stress_events_organization_id'), table_name='stress_events')
    op.drop_index(op.f('ix_stress_events_flock_id'), table_name='stress_events')
    op.drop_table('stress_events')
    op.drop_index(op.f('ix_predictions_organization_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_flock_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_outbreaks_organization_id'), table_name='outbreaks')
    op.drop_index(op.f('ix_outbreaks_flock_id'), table_name='outbreaks')
    op.drop_table('outbreaks')
    op.drop_index(op.f('ix_medications_organization_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_flock_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_kpi_snapshots_organization_id'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_flock_id'), table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_feed_consumption_organization_id'), table_name='feed_consumption')
    op.drop_index(op.f('ix_feed_consumption_flock_id'), table_name='feed_consumption')
    op.drop_table('feed_consumption')
    op.drop_index(op.f('ix_daily_production_organization_id'), table_name='daily_production')
    op.drop_index(op.f('ix_daily_production_flock_id'), table_name='daily_production')
    op.drop_index(op.f('ix_daily_production_date'), table_name='daily_production')
    op.drop_table('daily_production')
    op.drop_index(op.f('ix_breed_curves_organization_id'), table_name='breed_curves')
    op.drop_index(op.f('ix_breed_curves_flock_id'), table_name='breed_curves')
    op.drop_table('breed_curves')
    op.drop_index(op.f('ix_receivables_organization_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_client_id'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_incomes_organization_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_client_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_flocks_organization_id'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_farm_id'), table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_weather_cache_organization_id'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_personnel_organization_id'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_logbook_entries_organization_id'), table_name='logbook_entries')
    op.drop_table('logbook_entries')
    op.drop_index(op.f('ix_iot_readings_organization_id'), table_name='iot_readings')
    op.drop_table('iot_readings')
    op.drop_index(op.f('ix_feed_purchases_organization_id'), table_name='feed_purchases')
    op.drop_table('feed_purchases')
    op.drop_index(op.f('ix_farms_organization_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_expenses_organization_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_environment_readings_organization_id'), table_name='environment_readings')
    op.drop_table('environment_readings')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_checklist_items_organization_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
